core/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),

    path('login/', views.login_view, name = 'login'),
    path('logout/', views.logout_view, name = 'logout'),
    path('dashboard/', views.dashboard, name='dashboard'),

    path('student/', views.students, name='student'),
    path('student/delete/<int:pk>', views.deleteStudent, name='deleteStudent'),

    path('room/', views.rooms, name='room'),
    path('room/delete/<int:pk>', views.deleteRoom, name='deleteRoom'),

       
    path('staff/', views.staff, name='staff'),
    path('staff/delete/<int:staff_id>', views.delete_staff, name = 'deleteStaff'),

    path('departments/', views.departments, name='departments'),
    path('departments/delete/<int:pk>', views.deleteDept, name='deleteDepartment'),

    path('departments/<str:dpt>/', views.program, name='program'),
    path('program/delete/<int:pk>/', views.deleteProgram, name='deleteProgram'),
    
    path('courses/<str:program>/', views.course, name='course'),
    path('course/delete/<int:pk>/', views.deleteCourse, name='deleteCourse'),
    path('timetable/', views.timetable, name='timetable'),
    path('scheduletimetable/', views.scheduletimetable, name='scheduletimetable'),


    path('settings/', views.settings, name='settings'),
]

student_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'student'

urlpatterns = [
        path('dashboard/', views.student_dashboard, name='dashboard'),
        path('departments/', views.student_departments, name='departments'),
        path('lecturers/', views.student_lecturers, name='lecturers'),
        path('rooms/', views.student_rooms, name='rooms'),
        path('login/', views.login_view, name = 'login'),
        path('logout/', views.logout_view, name = 'logout'),
        path('settings/', views.settings, name='settings'),
    ]

timetable/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('student/', include('student_app.urls')),
    path('staff/', include('staff_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/students/login.html
{% load static%}

<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Time Table Generator</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="{% static 'vendors/feather/feather.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/ti-icons/css/themify-icons.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/css/vendor.bundle.base.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css'%}">

  <!-- endinject -->
  <!-- Plugin css for this page -->
  <link rel="stylesheet" href="{% static 'vendors/datatables.net-bs4/dataTables.bootstrap4.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/ti-icons/css/themify-icons.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'js/select.dataTables.min.css' %}">
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="{% static 'css/vertical-layout-light/style.css' %}">
  <!-- <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet"> -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

  <!-- endinject -->
  <link rel="shortcut icon" href="images/favicon.png" />
</head>

<body>

  <div class="container-scroller">
    <nav class="navbar col-lg-12 col-12 p-0 fixed-top">
      <div class="navbar-menu-wrapper d-flex align-items-center justify-content-between w-100">
          <div class="navbar-brand-wrapper">
              <a class="navbar-brand brand-logo ml-3 d-flex align-items-center my-2" href="#">
                  <img src="{% static 'images/timetable/logolira.png' %}" class="mr-2" alt="Lira University" />
                  <p class="text-primary text-bolder" style="font-weight: bolder;font-size: x-large;">Time Table Generator</p>
              </a>
              <a class="navbar-brand brand-logo-mini" href="#">
                  <img src="{% static 'images/timetable/logolira.png' %}" alt="logo" />
              </a>
          </div>
       
        
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button"
          data-toggle="offcanvas">
          <span class="icon-menu"></span>
        </button>
      </div>
    </nav>
    <div class="container-fluid full-page-wrapper" style="margin-top: 60px;">
      <!-- action notification -->
      <div id="notification" class="notification">Action was successful!</div>
      <!-- end notification -->
      <div class="content-wrapper d-flex align-items-center auth px-0">
        <div class="row w-100 mx-0">
          <div class="col-lg-4 mx-auto">
            <div class="auth-form-light text-left py-5 px-4 px-sm-5">
              <div class="brand-logo text-center">
                <img src="{% static 'images/timetable/logolira.png' %}" width="50" height="120" alt="logo">
              </div>
              <h4>Hello! Welcome Back</h4>
              <h6 class="font-weight-light">Sign in to continue.</h6>
              {% if messages %}
              {% for message in messages %}
              <h6{% if message.tags %} class="{{ message.tags }} text-danger" {% endif %}>{{ message }}</h6>
              {% endfor %}
              {% endif %}
              <form class="pt-3" method="POST">
                {% csrf_token%}
                <div class="form-group">
                  <input type="text" name="reg_no" class="form-control form-control-lg" id="exampleInputEmail1" placeholder="Registration Number">
                </div>
                <div class="form-group">
                  <input type="password" name="password" class="form-control form-control-lg" id="exampleInputPassword1" placeholder="Password">
                </div>
                <div class="mt-3">
                  <input type="submit" class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn" value="Login" onclick="performAction()">
                </div>
                <div class="my-2 d-flex justify-content-between align-items-center">
                  
                  <a href="#" class="auth-link text-black">Forgot password?</a>
                </div>

               
              </form>
              <a href="{%url 'core:home'%}" class="text-black nav-link text-center">Back to main</a>
            </div>
          </div>
        </div>
      </div>
      <!-- content-wrapper ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->
 <!-- plugins:js -->
 <script src="{% static 'vendors/js/vendor.bundle.base.js' %}"></script>
 <!-- endinject -->
 <!-- Plugin js for this page -->
 <script src="{% static 'vendors/chart.js/Chart.min.js' %}"></script>
 <script src="{% static 'vendors/datatables.net/jquery.dataTables.js' %}"></script>
 <script src="{% static 'vendors/datatables.net-bs4/dataTables.bootstrap4.js' %}"></script>
 <script src="{% static 'js/dataTables.select.min.js' %}"></script>
 <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
 <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
 <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


 <!-- End plugin js for this page -->
 <!-- inject:js -->
 <script src="{% static 'js/off-canvas.js' %}"></script>
 <script src="{% static 'js/hoverable-collapse.js' %}"></script>
 <script src="{% static 'js/template.js' %}"></script>
 <script src="{% static 'js/settings.js' %}"></script>
 <script src="{% static 'js/todolist.js' %}"></script>
 <script src="{% static 'js/notification.js' %}"></script>
 <!-- endinject -->
 <!-- Custom js for this page-->
 <script src="{% static 'js/dashboard.js' %}"></script>
 <script src="{% static 'js/Chart.roundedBarCharts.js' %}"></script>
 <!-- End custom js for this page-->
</body>

</html>

templates/students/settings.html
{% extends 'students/student_layout.html'%}

{% block content %}
<br />


<a href="#" class="btn btn-primary m-3" data-toggle="modal" data-target="#edit">Edit Profile</a>

<div class="col-lg-12 grid-margin stretch-card">
  <div class="card">
    <div class="card-body">
      <div class="table-responsive pt-3">
        <table class="table table-secondary table-striped">
          <thead>
            <tr>              
              <th>Full name</th>
              <th>Email</th>
            </tr>
          </thead>
          <tbody>
            <tr>              
              <td>KUSEMERERWA EDSON</td>
              <td>esonkusemererwa2000@gmail.com</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<!-- edit profile -->
<div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="exampleModalLabel">Edit Profile</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="card">
        <div class="card-body">
          <form class="forms-sample" method="POST">
            {% csrf_token %}
            <div class="form-group">
              <label for="fname">Full Name</label>
              <input name="fname" required type="text" class="form-control" id="fname"
                placeholder="Full Name" />
            </div>
            <div class="form-group">
              <label for="email">Email</label>
              <input name="email" required type="email" class="form-control" id="email"
                placeholder="Email" />
            </div>

            <div class="form-group">
              <label for="exampleInputPassword1">Password</label>
              <input name="password" required type="password" class="form-control" id="exampleInputPassword1"
                placeholder="Password" />
            </div>
            <div class="form-group">
              <label for="exampleInputConfirmPassword1">Confirm Password</label>
              <input name="conf_password" required type="password" class="form-control"
                id="exampleInputConfirmPassword1" placeholder="Confirm Password" />
            </div>

            <button type="submit" class="btn btn-primary mr-2" onclick="performAction()">Submit</button>
            <button type="reset" data-dismiss="modal" class="btn btn-secondary">
              Cancel
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{%endblock%}

templates/students/student.html
hello

templates/students/student_dashboard.html
{% extends 'students/student_layout.html'%}
{%block content%}
<h1 class="text-center">Students Dashboard</h1>
<div class="content-wrapper">
    <div class="row">
        <div class="col-md-12 grid-margin">
            <div class="row">
                <div class="col-12 col-xl-8 mb-4 mb-xl-0">
                    <h3 class="font-weight-bold">Welcome Back!</h3>
                    <h6 class="font-weight-normal mb-0">Thank you for using our timetable generator system!</h6>
                </div>
                <div class="col-12 col-xl-4">
                    <div class="card" style="max-width: 300px; border-radius: 8px;">
                        <div class="d-flex card-body"><h3 class="text-center text-bolder">Today</h3>
                            <div class="text-center text-bolder ml-5 my-2" id="current-date"></div>
                    </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 grid-margin transparent">
            <div class="row">
                <div class="col-md-6 mb-4 stretch-card transparent">
                    <div class="card card-dark-blue">
                        <div class="card-body">
                            <!-- Displayed based on the courses assiggned to that particular lecturer signed in -->
                            <p class="mb-4">Academic Year</p>
                            <p class="fs-30 mb-2">2024/2025</p>

                        </div>
                    </div>
                </div>
                <div class="col-md-6 mb-4 stretch-card transparent">
                    <div class="card bg-danger">
                        <div class="card-body text-white">
                            <p class="mb-4">Curent Semester</p>
                            <p class="fs-30 mb-2">Semester 2</p>
                        </div>
                    </div>
                </div>
            </div>
          
        </div>
        <div class="col-md-6 grid-margin transparent">
            <div class="row">
                <div class="col-md-6 mb-4 stretch-card transparent">
                    <div class="card bg-dark">
                        <div class="card-body text-white">
                            <p class="mb-4">Total Classes this Week</p>
                            <p class="fs-30 mb-2">3</p>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
</div>
{%endblock%}

templates/students/student_departments.html
{% extends 'students/student_layout.html'%}

{% block content %}
Departments
<br>
<div class="card p-3 my-3 bg-white">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Department Name</th>
                <th>Department Code</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for d in departments %}
            <tr>
                <td><a href="{% url 'core:program' dpt=d.pk %}">{{ d.department_name }}</a></td>
                <td>{{ d.department_code }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{%endblock%}

templates/students/student_layout.html
{% load static%}

<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Time Table Generator</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="{% static 'vendors/feather/feather.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/ti-icons/css/themify-icons.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/css/vendor.bundle.base.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css'%}">
  <script src="{% static 'js/currentdate.js' %}"></script>


  <!-- endinject -->
  <!-- Plugin css for this page -->
  <link rel="stylesheet" href="{% static 'vendors/datatables.net-bs4/dataTables.bootstrap4.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/ti-icons/css/themify-icons.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'js/select.dataTables.min.css' %}">
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="{% static 'css/vertical-layout-light/style.css' %}">
  <!-- <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet"> -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

  <!-- endinject -->
  <link rel="shortcut icon" href="images/favicon.png" />
</head>

<body>
  <div class="container-scroller">
    <!-- partial:partials/_navbar.html -->
    <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
      <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
        <a class="navbar-brand brand-logo ml-5 " href="#"><img src="{% static 'images/timetable/logolira.png' %}" class="mr-2" alt="Lira University" />TTG</a>
        <a class="navbar-brand brand-logo-mini" href="#"><img src="{% static 'images/timetable/logolira.png' %}"
            alt="logo" /></a>
      </div>
      <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
        <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
          <span class="icon-menu"></span>
        </button>
      
        <ul class="navbar-nav navbar-nav-right">
          <li class="nav-item dropdown">
            <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="{% url 'student:settings'%}"> 
              <i class="ti-settings  mx-0"></i>
              <!-- <span class="count"></span> -->
            </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list"
              aria-labelledby="notificationDropdown">
              <p class="mb-0 font-weight-normal float-left dropdown-header">Notifications</p>
              <a class="dropdown-item preview-item">
                <div class="preview-thumbnail">
                  <div class="preview-icon bg-success">
                    <i class="ti-info-alt mx-0"></i>
                  </div>
                </div>
                <div class="preview-item-content">
                  <h6 class="preview-subject font-weight-normal">Application Error</h6>
                  <p class="font-weight-light small-text mb-0 text-muted">
                    Just now
                  </p>
                </div>
              </a>
              <a class="dropdown-item preview-item">
                <div class="preview-thumbnail">
                  <div class="preview-icon bg-warning">
                    <i class="ti-settings mx-0"></i>
                  </div>
                </div>
                <div class="preview-item-content">
                  <h6 class="preview-subject font-weight-normal">Settings</h6>
                  <p class="font-weight-light small-text mb-0 text-muted">
                    Private message
                  </p>
                </div>
              </a>
              <a class="dropdown-item preview-item">
                <div class="preview-thumbnail">
                  <div class="preview-icon bg-info">
                    <i class="ti-user mx-0"></i>
                  </div>
                </div>
                <div class="preview-item-content">
                  <h6 class="preview-subject font-weight-normal">New user registration</h6>
                  <p class="font-weight-light small-text mb-0 text-muted">
                    2 days ago
                  </p>
                </div>
              </a>
            </div>
          </li>
         
        </ul>
        
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button"
          data-toggle="offcanvas">
          <span class="icon-menu"></span>
        </button>
      </div>
    </nav>
    <!-- partial -->
    <div class="container-fluid page-body-wrapper">
      <!-- notification div -->
      <div id="notification" class="notification">Action was successful!</div>


      <!-- partial:partials/_sidebar.html -->
      <nav class="sidebar sidebar-offcanvas position-fixed" id="sidebar">
        <ul class="nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'student:dashboard'%}">
              <i class="icon-grid menu-icon"></i>
              <span class="menu-title">Dashboard</span>
            </a>
          </li>
          

       
          <li class="nav-item">
            <a class="nav-link" href="{% url 'student:dashboard' %}">
              <i class="fa-solid fa-clock"></i>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              <span class="menu-title">Time Table</span>

            </a>
          </li>
 
          
          <hr>
          <br>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'student:logout' %}">
              <i class="icon-lock menu-icon"></i>
              <span class="menu-title" onclick="performAction()">Logout</span>

            </a>
          </li>


        </ul>
      </nav>
      <!-- partial -->
      <div class="main-panel" style="margin-left: 250px;">
        <div class="content-wrapper">
          {% block content%}
          {% endblock%}
        </div>
      </div>
    </div>
    <!-- page-body-wrapper ends -->

    <!-- settings modal -->
    <div class="modal fade" id="settings" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
      <div class="modal-dialog" role="document">
          <div class="modal-content">
              <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Update Settings</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                  </button>
              </div>
              <form action="" method="POST">
                  {% csrf_token %}
                  <div class="modal-body">
                      <input type="email" placeholder="Email" name="email" class="form-control my-2" required>
                      <input type="password" placeholder="Password" name="password" class="form-control my-2" required>
                      <input type="passwordConfirm" placeholder="Confirm Password" name="passwordConfirm" class="form-control my-2" required>
                  </div>
                  <div class="modal-footer">
                      <button type="reset" class="btn btn-secondary" data-dismiss="modal">Close</button>
                      <button type="submit" class="btn btn-primary" onclick="performAction()">Save</button>
                  </div>
              </form>
          </div>
      </div>
    </div>
  </div>
  <!-- container-scroller -->

  <!-- plugins:js -->
  <script src="{% static 'vendors/js/vendor.bundle.base.js' %}"></script>
  <!-- endinject -->
  <!-- Plugin js for this page -->
  <script src="{% static 'vendors/chart.js/Chart.min.js' %}"></script>
  <script src="{% static 'vendors/datatables.net/jquery.dataTables.js' %}"></script>
  <script src="{% static 'vendors/datatables.net-bs4/dataTables.bootstrap4.js' %}"></script>
  <script src="{% static 'js/dataTables.select.min.js' %}"></script>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


  <!-- End plugin js for this page -->
  <!-- inject:js -->
  <script src="{% static 'js/off-canvas.js' %}"></script>
  <script src="{% static 'js/hoverable-collapse.js' %}"></script>
  <script src="{% static 'js/template.js' %}"></script>
  <script src="{% static 'js/settings.js' %}"></script>
  <script src="{% static 'js/todolist.js' %}"></script>
  <script src="{% static 'js/notification.js' %}"></script>
  <!-- endinject -->
  <!-- Custom js for this page-->
  <script src="{% static 'js/dashboard.js' %}"></script>
  <script src="{% static 'js/Chart.roundedBarCharts.js' %}"></script>
  <!-- End custom js for this page-->
</body>

</html>

templates/students/student_lecturers.html
{% extends 'students/student_layout.html'%}

{% block content %}
Lecturers
<br>
<div class="card p-3 my-3 bg-white">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Lecturer Name</th>
                <th>Lecturer Number</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Ojuka Nelson</td>
                <td>lcs001</td>
            </tr>
        </tbody>
    </table>
</div>
{%endblock%}

templates/students/student_rooms.html
{% extends 'students/student_layout.html'%}

{% block content %}
Rooms
<br />

<!-- add room -->
  <div class="card">
    <div class="card-body">

      <div class="table-responsive pt-3">
        <table class="table table-secondary table-striped">
          <thead>
            <tr>
              <th>
                Room Name
              </th>
              <th>
                Room Capacity
              </th>
              <th>
                Location
              </th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                Educ Comp Lab
              </td>
              <td>
                55 Seats
              </td>
              <td>
                Faculty of Education 3rd floor
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>



<!-- Add room -->
<div class="modal fade" id="addRoom" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="exampleModalLabel">Add Room</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="card">
        <div class="card-body">
          <form class="forms-sample" method="POST">
            {% csrf_token %}


            <div class="form-group">
              <label for="exampleInputUsername1">Room Name</label>
              <input name="room_name" required type="text" class="form-control" id="exampleInputUsername1"
                placeholder="Room name" />
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Room Capacity</label>
              <input type="text" name="room_cap" required class="form-control" id="exampleInputEmail1"
                placeholder="Room Capacity" />
            </div>
            <div class="form-group">
              <label for="location">Room Location</label>
              <input type="text" name="room_location" required class="form-control" id="location"
                placeholder="Location" />
            </div>
            <button type="submit" class="btn btn-primary mr-2" onclick="performAction()">
              Add Room
            </button>
            <button type="reset" data-dismiss="modal" class="btn btn-light">
              Cancel
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% for r in rooms %}
<!-- edit room -->
<div class="modal fade" id="editRoom{{r.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="exampleModalLabel">Edit Room</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="card">
        <div class="card-body">
          <form class="forms-sample" method="POST">
            {% csrf_token %}

            <input type="hidden" name="room_id" value="{{r.id}}" id="">
            <div class="form-group">
              <label for="exampleInputUsername1">Room Name</label>
              <input name="room_name" value="{{r.room_name}}" required type="text" class="form-control"
                id="exampleInputUsername1" placeholder="Room Name" />
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Room Capacity</label>
              <input type="text" value="{{r.capacity}}" name="room_cap" required class="form-control"
                id="exampleInputEmail1" placeholder="Room Capacity" />
            </div>
            <div class="form-group">
              <label for="location">Room Location</label>
              <input type="text" value="{{r.location}}" name="room_location" required class="form-control" id="location"
                placeholder="Location" />
            </div>
            <button type="submit" class="btn btn-primary mr-2" onclick="performAction()">
              Edit Room
            </button>
            <button type="reset" data-dismiss="modal" class="btn btn-light">
              Cancel
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{%endfor%}
{%endblock%}