core/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),

    path('login/', views.login_view, name = 'login'),
    path('logout/', views.logout_view, name = 'logout'),
    path('dashboard/', views.dashboard, name='dashboard'),

    path('student/', views.students, name='student'),
    path('student/delete/<int:pk>', views.deleteStudent, name='deleteStudent'),

    path('room/', views.rooms, name='room'),
    path('room/delete/<int:pk>', views.deleteRoom, name='deleteRoom'),

       
    path('staff/', views.staff, name='staff'),
    path('staff/delete/<int:staff_id>', views.delete_staff, name = 'deleteStaff'),

    path('departments/', views.departments, name='departments'),
    path('departments/delete/<int:pk>', views.deleteDept, name='deleteDepartment'),

    path('departments/<str:dpt>/', views.program, name='program'),
    path('program/delete/<int:pk>/', views.deleteProgram, name='deleteProgram'),
    
    path('courses/<str:program>/', views.course, name='course'),
    path('course/delete/<int:pk>/', views.deleteCourse, name='deleteCourse'),
    path('timetable/', views.timetable, name='timetable'),
    path('scheduletimetable/', views.scheduletimetable, name='scheduletimetable'),


    path('settings/', views.settings, name='settings'),
]

timetable/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('student/', include('student_app.urls')),
    path('staff/', include('staff_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/pages/course.html
{% extends 'core/layout.html'%}

{% block content %}
<div class="container">
    <h3 class="text-center">{{ program.program_name }} ({{ program.program_code }})</h3>
    <p>Course Units</p>
    <a href="#" class="btn btn-primary m-3" data-toggle="modal" data-target="#addCourse">Add Course</a>

    </div>
    {% for year, courses_in_year in courses_by_year.items %}
    <div class="card p-3 my-3 bg-white">
        <h5>Year {{ year }}</h5>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Code</th>
                    <th>Course Unit</th>
                    <th>Lecturer</th>
                    <th>Credits</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for c in courses %}
                {% if c.course_year == year %}
                <tr>
                    <td>{{ c.course_code }}</td>
                    <td>{{ c.course_name }}</td>
                    <td>{{c.course_lecturer.fullname}}</td>
                    <td>{{ c.credit }}</td>
                    <td>
                        <a href="#" data-toggle="modal" class="btn btn-warning" data-target="#editCourse{{ c.id }}">Edit</a>
                        <a href="{% url 'core:deleteCourse' pk=c.id %}" class="btn btn-danger" onclick="return(confirm('Are you sure you want to delete this Course?'))">Delete</i></a>
                    </td>
                </tr>
                {% endif %}
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% endfor %}
</div>


{% for c in courses %}
<!-- edit course -->
<div class="modal fade" id="editCourse{{c.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit {{c.course_name}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{% url 'core:course' program=program.pk %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="cId" value="{{c.pk}}">
                <div class="modal-body">
                    <input type="text" placeholder="Course Code" name="c_code" class="form-control my-2" value="{{c.course_code}}" required>
                    <input type="text" placeholder="Course Name" name="c_name" class="form-control my-2" value="{{c.course_name}}" required>
                    <input type="number" placeholder="Credit units" name="c_credits" class="form-control my-2" value="{{c.credit}}" required>
                    <select name="course_year" class="form-control my-2">
                        <option value="1 I" {% if c.course_year == '1 I' %} selected {% endif %}>Year 1, Semister One</option>
                        <option value="1 II" {% if c.course_year == '1 II' %} selected {% endif %}>Year 1, Semister Two</option>
                        <option value="2 I" {% if c.course_year == '2 I' %} selected {% endif %}>Year 2, Semister One</option>
                        <option value="2 II" {% if c.course_year == '2 II' %} selected {% endif %}>Year 2, Semister Two</option>
                        <option value="3 I" {% if c.course_year == '3 I' %} selected {% endif %}>Year 3, Semister One</option>
                        <option value="3 II" {% if c.course_year == '3 II' %} selected {% endif %}>Year 3, Semister Two</option>
                        <option value="4 I" {% if c.course_year == '4 I' %} selected {% endif %}>Year 4, Semister One</option>
                        <option value="4 II" {% if c.course_year == '4 II' %} selected {% endif %}>Year 4, Semister Two</option>
                        <option value="5 I" {% if c.course_year == '5 I' %} selected {% endif %}>Year 5, Semister One</option>
                        <option value="5 II" {% if c.course_year == '5 II' %} selected {% endif %}>Year 5, Semister Two</option>
                    </select>
                    <select name="course_lecturer" id="" class="form-control my-2" required>
                        <option value="">None</option>
                        {% for s in staff %}
                        <option value="{{s.id}}" {% if c.course_lecturer.id == s.id %} selected {%endif%}>{{s.fullname}}</option>
                        {%endfor%}
                    </select>

                    <textarea name="c_desc" id="" cols="30" rows="5" class="form-control"
                        placeholder="Description">{{c.description}}</textarea>
                </div>
                <div class="modal-footer">
                    <button type="reset" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Update</button>
                </div>
            </form>
        </div>
    </div>
</div>

{%endfor%}

<!-- add course -->
<div class="modal fade" id="addCourse" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add Course</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{% url 'core:course' program=program.pk %}" method="POST">
                {% csrf_token %}
                <div class="modal-body">
                    <input type="text" placeholder="Course Code" name="c_code" class="form-control my-2" required>
                    <input type="text" placeholder="Course Name" name="c_name" class="form-control my-2" required>
                    <input type="number" placeholder="Credit units" name="c_credits" class="form-control my-2" required>
                    <select name="course_year" id="" class="form-control my-2" required>
                        <option value="">Choose Year</option>
                        <option value="1 I">Year 1, Semister One</option>
                        <option value="1 II">Year 1, Semister Two</option>
                        <option value="2 I">Year 2, Semister One</option>
                        <option value="2 II">Year 2, Semister Two</option>
                        <option value="3 I">Year 3, Semister One</option>
                        <option value="3 II">Year 3, Semister Two</option>
                        <option value="4 I">Year 4, Semister One</option>
                        <option value="4 II">Year 4, Semister One</option>
                        <option value="5 I">Year 5, Semister Two</option>
                        <option value="5 II">Year 5, Semister Two</option>
                    </select>

                    <select name="course_lecturer" id="" class="form-control my-2" required>
                        <option value="">Choose course Lecturer</option>
                        {% for s in staff %}
                        <option value="{{s.id}}">{{s.fullname}}</option>
                        {%endfor%}
                    </select>

                    <textarea name="c_desc" id="" cols="30" rows="5" class="form-control"
                        placeholder="Description"></textarea>
                </div>
                <div class="modal-footer">
                    <button type="reset" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
{%endblock%}

templates/pages/program.html
{% extends 'core/layout.html'%}

{% block content %}
<div class="col-lg-12 stretch-card">

    <div class="card p-3 my-3 bg-white">
        <h3 class="text-center">{{ department.department_name }} <br>({{ department.department_code }})</h3>
        <span><h5>Programs</h5></span>
    <div>
        <a href="#" class="btn btn-primary m-3" data-toggle="modal" data-target="#addProgram">Add Program</a>
    
    </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-striped ">
                    <thead>
                        <tr>
                            <th>Program Name</th>
                            <th>Program Code</th>
                            <th class="text-center">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for p in programs %}
                        {% if p.department.pk == department.pk %}
                        <tr>
                            <td><a class="nav-link" href="{% url 'core:course' program=p.pk %}">{{ p.program_name }}</a></td>
                            <td>{{ p.program_code }}</td>
                            <td class="text-center">
                                <a href="#" data-toggle="modal" data-target="#editProgram{{ p.id }}" class="btn btn-warning" >Edit</a>
                                <a href="{% url 'core:deleteProgram' pk=p.id %}" onclick="return(confirm('Are you sure you want to delete this Program?'))" class="btn btn-danger">Delete</i></a>
                            </td>
                        </tr>
                        {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
       
    </div>
</div>


<!-- edit program -->
{%for p in programs %}
<div class="modal fade" id="editProgram{{p.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit {{p.program_name}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{% url 'core:program' dpt=department.pk %}" method="POST">
                {% csrf_token %}
                <input type="hidden" value="{{p.id}}" name="prgId">
                <div class="modal-body">
                    <input type="text" placeholder="Program Code" name="prgcode" value="{{p.program_code}}"
                        class="form-control my-2" required>
                    <input type="text" placeholder="Program Name" name="prgname" value="{{p.program_name}}"
                        class="form-control my-2" required>
                </div>
                <div class="modal-footer">
                    <button type="reset" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Update</button>
                </div>
            </form>
        </div>
    </div>
</div>
{%endfor%}


<!-- add program -->
<div class="modal fade" id="addProgram" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add program</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{% url 'core:program' dpt=department.pk %}" method="POST">
                {% csrf_token %}
                <div class="modal-body">
                    <input type="text" placeholder="Program Code" name="prgcode" class="form-control my-2" required>
                    <input type="text" placeholder="Program Name" name="prgname" class="form-control my-2" required>
                </div>
                <div class="modal-footer">
                    <button type="reset" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
{%endblock%}

templates/pages/scheduletimetable.html
{% extends 'core/layout.html'%}

{% block content %}

<div class="content-wrapper">
    <div class="modal fade" id="ttschedule" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="exampleModalLabel">Schedule Timetable</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="card">
                <div class="card-body">
                    <form action="{% url 'core:scheduletimetable' %}" method="POST">

                        <div class="form-group">
                            <label for="">Staff</label>
                            <select name="department" required class="js-example-basic-single w-100 form-control">
                                <option value="">Choose Staff</option>
                                
                                <option value="">option1</option>
                                
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="">Courses</label>
                            <select name="department" required class="js-example-basic-single w-100 form-control">
                                <option value="">Choose Course</option>
                                
                                <option value="">option1</option>
                                
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="">Rooms</label>
                            <select name="department" required class="js-example-basic-single w-100 form-control">
                                <option value="">Choose Room</option>
                                
                                <option value="">option1</option>
                                
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="">Time Slots</label>
                            <select name="department" required class="js-example-basic-single w-100 form-control">
                                <option value="">Choose Timeslot</option>
                                
                                <option value="">option1</option>
                                
                            </select>
                        </div>
                        
                        <button type="submit" class="btn btn-primary mr-2" onclick="performAction()">Save</button>
                        <button type="reset" data-dismiss="modal" class="btn btn-warning">
                            Cancel
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
  
    

</div>
{%endblock%}