core/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),

    path('login/', views.login_view, name = 'login'),
    path('logout/', views.logout_view, name = 'logout'),
    path('dashboard/', views.dashboard, name='dashboard'),

    path('student/', views.students, name='student'),
    path('student/delete/<int:pk>', views.deleteStudent, name='deleteStudent'),

    path('room/', views.rooms, name='room'),
    path('room/delete/<int:pk>', views.deleteRoom, name='deleteRoom'),

       
    path('staff/', views.staff, name='staff'),
    path('staff/delete/<int:staff_id>', views.delete_staff, name = 'deleteStaff'),

    path('departments/', views.departments, name='departments'),
    path('departments/delete/<int:pk>', views.deleteDept, name='deleteDepartment'),

    path('departments/<str:dpt>/', views.program, name='program'),
    path('program/delete/<int:pk>/', views.deleteProgram, name='deleteProgram'),
    
    path('courses/<str:program>/', views.course, name='course'),
    path('course/delete/<int:pk>/', views.deleteCourse, name='deleteCourse'),
    path('timetable/', views.timetable, name='timetable'),
    path('scheduletimetable/', views.scheduletimetable, name='scheduletimetable'),


    path('settings/', views.settings, name='settings'),
]

timetable/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('student/', include('student_app.urls')),
    path('staff/', include('staff_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from store.models import Department, Program, Course, Staff, Student, Room
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate

def home(request):
    return render(request, 'index.html')

def about(request):
    return render(request, 'about.html')

def logout_view(request):
    logout(request)
    messages.success(request, 'Logged out successfully.')
    return redirect('core:login')

def login_view(request):
    if request.user.is_authenticated:
        return redirect('core:dashboard')

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            
            return redirect('core:dashboard')
        else:
            messages.error(request, 'Invalid Username or Password.')

    return render(request, 'core/login.html')

def dashboard(request):
    if not request.user.is_authenticated:
        
        return redirect('core:login')

    num_dpt = Department.objects.all().count()
    num_prog = Program.objects.all().count()
    num_course = Course.objects.all().count()
    num_staff = Staff.objects.all().count()
    num_student = Student.objects.all().count()
    num_room = Room.objects.all().count()

    context = {
        'num_dpt': num_dpt,
        'num_prog': num_prog,
        'num_course': num_course,
        'num_staff': num_staff,
        'num_student': num_student,
        'num_room': num_room
    }
    return render(request, 'core/dashboard.html', context)

def students(request):
    if not request.user.is_authenticated:
      
        return redirect('core:login')

    programs = Program.objects.all()
    students = Student.objects.all().order_by('-id')

    if request.method == "POST":
        student_id = request.POST.get('student_id')
        program = request.POST.get('program')
        fname = request.POST.get('fname')
        lname = request.POST.get('lname')
        email = request.POST.get('email')
        reg_no = request.POST.get('reg_no')
        password = request.POST.get('password')
        conf_pass = request.POST.get('conf_password')

        prog = Program.objects.get(pk=program)

        if student_id:
            if password == conf_pass:
                student = Student.objects.get(pk=student_id)
                student.first_name = fname
                student.last_name = lname
                student.email = email
                student.program = prog
                student.reg_no = reg_no
                student.save()
                messages.success(request, 'Student updated successfully.')
            else:
                messages.error(request, "Passwords do not match.")
        else:
            if password == conf_pass:
                student = Student.objects.create(reg_no=reg_no, first_name=fname, last_name=lname, email=email, program=prog, password=password)
                student.save()
                messages.success(request, 'Student created successfully.')
            else:
                messages.error(request, "Passwords do not match.")

    context = {
        'programs': programs,
        'students': students,
    }
    return render(request, 'core/student.html', context)

def deleteStudent(request, pk):
    if not request.user.is_authenticated:
        messages.error(request, 'You need to be logged in to view this page.')
        return redirect('core:login')

    student = get_object_or_404(Student, pk=pk)
    student.delete()
    messages.success(request, 'Student deleted successfully.')
    return redirect('core:student')

def staff(request):
    if not request.user.is_authenticated:
        messages.error(request, 'You need to be logged in to view this page.')
        return redirect('core:login')

    departments = Department.objects.all()
    staffs = Staff.objects.all().order_by('-id')

    if request.method == "POST":
        staff_id = request.POST.get('staff_id')
        role = request.POST.get('role')
        dpt = request.POST.get('department')
        fname = request.POST.get('fname')
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        conf_pass = request.POST.get('conf_password')

        department = Department.objects.get(pk=dpt)

        if staff_id:
            if password == conf_pass:
                staff = Staff.objects.get(pk=staff_id)
                staff.fullname = fname
                staff.username = username
                staff.email = email
                staff.role = role
                staff.password = password
                staff.department = department
                staff.save()
                messages.success(request, 'Staff updated successfully.')
            else:
                messages.error(request, "Passwords do not match.")
        else:
            if password == conf_pass:
                staff = Staff.objects.create(department=department, fullname=fname, username=username, email=email, password=password)
                staff.save()
                messages.success(request, 'Staff created successfully.')
            else:
                messages.error(request, "Passwords do not match.")

    context = {
        'departments': departments,
        'staffs': staffs,
    }
    return render(request, 'core/staff.html', context)

def delete_staff(request, staff_id):
    if not request.user.is_authenticated:
       
        return redirect('core:login')

    staff = get_object_or_404(Staff, pk=staff_id)
    staff.delete()
    
    return redirect('core:staff')

def feedback(request):
    if not request.user.is_authenticated:
        
        return redirect('core:login')

    return render(request, 'core/feedback.html')

def course(request, program):
    if not request.user.is_authenticated:
        
        return redirect('core:login')

    program = get_object_or_404(Program, pk=program)
    courses = Course.objects.filter(program=program)
    staff = Staff.objects.all()

    courses_by_year = {}
    for course in courses:
        year = course.course_year
        if year not in courses_by_year:
            courses_by_year[year] = []
        courses_by_year[year].append(course)

    if request.method == "POST":
        cId = request.POST.get('cId')
        c_code = request.POST.get('c_code')
        c_name = request.POST.get('c_name')
        c_credits = request.POST.get('c_credits')
        c_desc = request.POST.get('c_desc')
        course_year = request.POST.get('course_year')
        c_lecturer = request.POST.get('course_lecturer')

        course_lecturer = Staff.objects.get(pk=c_lecturer)

        if cId:
            course = Course.objects.get(pk=cId)
            course.course_code = c_code
            course.course_name = c_name
            course.credit = c_credits
            course.course_year = course_year
            course.description = c_desc
            course.course_lecturer = course_lecturer
            course.save()
            
        else:
            course = Course.objects.create(course_name=c_name, course_code=c_code, description=c_desc, program=program, credit=c_credits, course_year=course_year, course_lecturer=course_lecturer)
            course.save()
            

        return redirect('core:course', program=program.pk)

    context = {
        'staff': staff,
        'program': program,
        'courses': courses,
        'courses_by_year': courses_by_year,
    }
    return render(request, "pages/course.html", context)

def deleteCourse(request, pk):
    if not request.user.is_authenticated:
        messages.error(request, 'You need to be logged in to view this page.')
        return redirect('core:login')

    course = get_object_or_404(Course, pk=pk)
    course.delete()
    messages.success(request, 'Course deleted successfully.')
    return redirect('core:course', program=course.program.id)

def program(request, dpt):
    if not request.user.is_authenticated:
        
        return redirect('core:login')

    department = get_object_or_404(Department, pk=dpt)
    programs = Program.objects.all()

    if request.method == "POST":
        prg_id = request.POST.get('prgId')
        progcode = request.POST.get('prgcode')
        progname = request.POST.get('prgname')

        if prg_id:
            program = Program.objects.get(pk=prg_id)
            program.program_code = progcode
            program.program_name = progname
            program.save()
            
        else:
            program = Program.objects.create(program_code=progcode, program_name=progname, department=department)
            program.save()
           

    context = {
        'department': department,
        'programs': programs,
    }
    return render(request, 'pages/program.html', context)

def deleteProgram(request, pk):
    if not request.user.is_authenticated:
        
        return redirect('core:login')

    program = get_object_or_404(Program, pk=pk)
    program.delete()
    
    return redirect('core:program', dpt=program.department.id)

def departments(request):
    if not request.user.is_authenticated:
        
        return redirect('core:login')

    departments = Department.objects.all()

    if request.method == "POST":
        dpt_id = request.POST.get('dtId')
        dpt_code = request.POST.get('dptcode')
        dpt_name = request.POST.get('dptname')
        

        if dpt_id:
            department = Department.objects.get(pk=dpt_id)
            department.department_code = dpt_code
            department.department_name = dpt_name
            department.save()
            
        else:
            department = Department.objects.create(department_code=dpt_code, department_name=dpt_name)
            department.save()
            

    context = {

templates/core/departments.html
{% extends 'core/layout.html'%}

{% block content %}
Departments
<br>
<a href="#" class="btn btn-primary m-3" data-toggle="modal" data-target="#addDepartment">Add department</a>


<div class="card p-3 my-3 bg-white">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Department Name</th>
                <th>Department Code</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for d in departments %}
            <tr>
                <td><a class="nav-link" href="{% url 'core:program' dpt=d.pk %}">{{ d.department_name }}</a></td>
                <td>{{ d.department_code }}</td>
                <td>
                    <a href="#" data-toggle="modal" data-target="#editDepartment{{ d.id }}" class="btn btn-warning">Edit</a>
                    <a href="{% url 'core:deleteDepartment' pk=d.id %}" onclick="return(confirm('Are you sure you want to delete this department?'))" class="btn btn-danger">Delete</i></a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>


<!-- edit department -->
{%for d in departments %}
<div class="modal fade" id="editDepartment{{d.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit {{d.department_name}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{% url 'core:departments' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" value="{{d.id}}" name="dtId">
                <div class="modal-body">
                    <input type="text" placeholder="Department Code" name="dptcode" value="{{d.department_code}}"
                        class="form-control my-2" required>
                    <input type="text" placeholder="Department Name" name="dptname" value="{{d.department_name}}"
                        class="form-control my-2" required>
                </div>
                <div class="modal-footer">
                    <button type="reset" class="btn btn-light" data-dismiss="modal" onclick="performAction()">Cancel</button>
                    <button type="submit" class="btn btn-primary" onclick="performAction()">Update</button>
                </div>
            </form>
        </div>
    </div>
</div>
{%endfor%}

<!-- add department -->
<div class="modal fade" id="addDepartment" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add Department</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{% url 'core:departments' %}" method="POST">
                {% csrf_token %}
                <div class="modal-body">
                    <input type="text" placeholder="Department Code" name="dptcode" class="form-control my-2" required>
                    <input type="text" placeholder="Department Name" name="dptname" class="form-control my-2" required>
                </div>
                <div class="modal-footer">
                    <button type="reset" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary" onclick="performAction()">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
{%endblock%}

templates/core/layout.html
{% load static%}

<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Time Table Generator</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="{% static 'vendors/feather/feather.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/ti-icons/css/themify-icons.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/css/vendor.bundle.base.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/mdi/css/materialdesignicons.min.css' %}">
  <!-- endinject -->
  <!-- Plugin css for this page -->
  <link rel="stylesheet" href="{% static 'vendors/datatables.net-bs4/dataTables.bootstrap4.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/ti-icons/css/themify-icons.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'js/select.dataTables.min.css' %}">
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="{% static 'css/vertical-layout-light/style.css' %}">
  <!-- <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet"> -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css'%}">

  <!-- endinject -->
  <link rel="shortcut icon" href="images/favicon.png" />
 

  <script>
    function showPopup(message) {
      alert(message);
    }
  </script>

</head>

<body>
  <div class="container-scroller">
    <!-- partial:partials/_navbar.html -->
    <nav class="navbar col-lg-12 col-12 p-0 fixed-top">
      <div class="navbar-menu-wrapper d-flex align-items-center justify-content-between w-100">
        <div class="navbar-brand-wrapper">
          <a class="navbar-brand brand-logo ml-3 d-flex align-items-center my-2" href="#">
            <img src="{% static 'images/timetable/logolira.png' %}" class="mr-2" alt="Lira University" />
            <img src="{% static 'images/timetable/tt.png' %}" alt="logo" />
          </a>
        </div>
        
        <ul class="navbar-nav navbar-nav-right">
          <li class="nav-item dropdown">
            <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="{% url 'core:settings'%}">
              <!-- data-toggle="modal" data-target="#settings" -->
              <i class="ti-settings mx-0"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="notificationDropdown">
              <p class="mb-0 font-weight-normal float-left dropdown-header">Notifications</p>
              
              <a class="dropdown-item preview-item">
                <div class="preview-thumbnail">
                  <div class="preview-icon bg-success">
                    <i class="ti-info-alt mx-0"></i>
                  </div>
                </div>
                <div class="preview-item-content">
                  <h6 class="preview-subject font-weight-normal">Application Error</h6>
                  <p class="font-weight-light small-text mb-0 text-muted">Just now</p>
                </div>
              </a>
              
              <a class="dropdown-item preview-item">
                <div class="preview-thumbnail">
                  <div class="preview-icon bg-warning">
                    <i class="ti-settings mx-0"></i>
                  </div>
                </div>
                <div class="preview-item-content">
                  <h6 class="preview-subject font-weight-normal">Settings</h6>
                  <p class="font-weight-light small-text mb-0 text-muted">Private message</p>
                </div>
              </a>
              
              <a class="dropdown-item preview-item">
                <div class="preview-thumbnail">
                  <div class="preview-icon bg-info">
                    <i class="ti-user mx-0"></i>
                  </div>
                </div>
                <div class="preview-item-content">
                  <h6 class="preview-subject font-weight-normal">New user registration</h6>
                  <p class="font-weight-light small-text mb-0 text-muted">2 days ago</p>
                </div>
              </a>
            </div>
          </li>
        </ul>
        
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
          <span class="icon-menu"></span>
        </button>
      </div>
    </nav>
    
    <!-- partial -->
    <div class="container-fluid page-body-wrapper">

      <!-- partial:partials/_sidebar.html -->
      <!-- <nav class="sidebar sidebar-offcanvas position-fixed" id="sidebar"> -->
      <nav class="sidebar sidebar-offcanvas position-fixed" id="sidebar">  
        <ul class="nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:dashboard'%}">
              <i class="icon-grid menu-icon"></i>
              <span class="menu-title">Dashboard</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:departments' %}">
              <i class="icon-layout menu-icon"></i>
              <span class="menu-title">Departments</span>

            </a>

          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:staff' %}">
              <i style="font-size: 15px; margin-right: 20px;" class="mdi mdi-human-greeting"></i>
              <span class="menu-title">Staff</span>

            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:student' %}">
              <i class="icon-head menu-icon"></i>
              <span class="menu-title">Students</span>

            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:room' %}">
              <i class="fa-solid fa-restroom"></i> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              <span class="menu-title">Rooms</span>

            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:timetable' %}">
              <i class="icon-head menu-icon"></i>
              <span class="menu-title">Timetable</span>

            </a>
          </li>
          <hr>
          <br>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:logout' %}">
              <i class="icon-lock menu-icon"></i>
              <span class="menu-title" onclick="performAction()">Logout</span>

            </a>
          </li>


        </ul>
      </nav>
      <!-- partial -->
      <div class="main-panel" style="margin-left: 250px;">
        <div class="content-wrapper">
          {% block content%}
          
          {% endblock%}
        </div>
      </div>
    </div>
    <!-- page-body-wrapper ends -->

    <!-- settings modal -->
    <div class="modal fade" id="settings" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
      <div class="modal-dialog" role="document">
          <div class="modal-content">
              <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Update Settings</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                  </button>
              </div>
              <form action="" method="POST">
                  {% csrf_token %}
                  <div class="modal-body">
                      <input type="email" placeholder="Email" name="email" class="form-control my-2" required>
                      <input type="password" placeholder="Password" name="password" class="form-control my-2" required>
                      <input type="passwordConfirm" placeholder="Confirm Password" name="passwordConfirm" class="form-control my-2" required>
                  </div>
                  <div class="modal-footer">
                      <button type="reset" class="btn btn-secondary" data-dismiss="modal">Close</button>
                      <button type="submit" class="btn btn-primary" onclick="performAction()">Save</button>
                  </div>
              </form>
          </div>
      </div>
    </div>
  </div>
  <div id="notification" class="notification">Successful!</div>

  <!-- container-scroller -->

  <!-- plugins:js -->
  <script src="{% static 'vendors/js/vendor.bundle.base.js' %}"></script>
  <!-- endinject -->
  <!-- Plugin js for this page -->
  <script src="{% static 'vendors/chart.js/Chart.min.js' %}"></script>
  <script src="{% static 'vendors/datatables.net/jquery.dataTables.js' %}"></script>
  <script src="{% static 'vendors/datatables.net-bs4/dataTables.bootstrap4.js' %}"></script>
  <script src="{% static 'js/dataTables.select.min.js' %}"></script>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


  <!-- End plugin js for this page -->
  <!-- inject:js -->
  <script src="{% static 'js/off-canvas.js' %}"></script>
  <script src="{% static 'js/hoverable-collapse.js' %}"></script>
  <script src="{% static 'js/template.js' %}"></script>
  <script src="{% static 'js/settings.js' %}"></script>
  <script src="{% static 'js/todolist.js' %}"></script>
  <!-- <script src="{% static 'js/notification.js' %}"></script> -->
  <script src="{% static 'js/currentdate.js' %}"></script>
  <!-- endinject -->
  <!-- Custom js for this page-->
  <script src="{% static 'js/dashboard.js' %}"></script>
  <script src="{% static 'js/Chart.roundedBarCharts.js' %}"></script>
  <!-- End custom js for this page-->

  {% if messages %}
  <script>
    function showPopup(message) {
      var popup = document.getElementById('popup');
      popup.innerText = message;
      popup.classList.add('show');
      setTimeout(function () {
        popup.classList.remove('show');
      }, 3000);
    }

    document.addEventListener("DOMContentLoaded", function () {
      var messagesContainer = document.getElementById('messages-container');
      var messages = messagesContainer.dataset.messages;
      if (messages) {
        messages = JSON.parse(messages);
        messages.forEach(function (message) {
          showPopup(message);
        });
      }
    });
  </script>
  {% endif %}
  
</body>

</html>

templates/core/room.html
{% extends 'core/layout.html'%} {% block content %} Rooms
<br />

<!-- add room -->
<a href="#" class="btn btn-primary m-3" data-toggle="modal" data-target="#addRoom">Add Room</a>
<div class="col-lg-12 grid-margin stretch-card">
  <div class="card">
    <div class="card-body">

      <div class="table-responsive pt-3">
        <table class="table table-secondary table-striped">
          <thead>
            <tr>
              <th>
                Room Name
              </th>
              <th>
                Room Capacity
              </th>
              <th>
                Location
              </th>
              <th>
                Action
              </th>
            </tr>
          </thead>
          <tbody>
            {% for r in rooms %}
            <tr>
              <td>
                {{r.room_name}}
              </td>
              <td>
                {{r.capacity}}
              </td>
              <td>
                {{r.location}}
              </td>
              <td>
                <a href="#" data-toggle="modal" data-target="#editRoom{{ r.id }}"
                  class="btn btn-warning">Edit</a>&nbsp;&nbsp;&nbsp;&nbsp;
                <a href="{% url 'core:deleteRoom' pk=r.id%}" onclick="return(confirm('Are you sure you want to delete this room?'))"
                  class="btn btn-danger">Delete</a>
              </td>
            </tr>
            {%endfor%}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>



<!-- Add room -->
<div class="modal fade" id="addRoom" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="exampleModalLabel">Add Room</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="card">
        <div class="card-body">
          <form class="forms-sample" method="POST">
            {% csrf_token %}


            <div class="form-group">
              <label for="exampleInputUsername1">Room Name</label>
              <input name="room_name" required type="text" class="form-control" id="exampleInputUsername1"
                placeholder="Room name" />
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Room Capacity</label>
              <input type="text" name="room_cap" required class="form-control" id="exampleInputEmail1"
                placeholder="Room Capacity" />
            </div>
            <div class="form-group">
              <label for="location">Room Location</label>
              <input type="text" name="room_location" required class="form-control" id="location"
                placeholder="Location" />
            </div>
            <button type="submit" class="btn btn-primary mr-2" onclick="performAction()">
              Add Room
            </button>
            <button type="reset" data-dismiss="modal" class="btn btn-light">
              Cancel
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% for r in rooms %}
<!-- edit room -->
<div class="modal fade" id="editRoom{{r.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="exampleModalLabel">Edit Room</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="card">
        <div class="card-body">
          <form class="forms-sample" method="POST">
            {% csrf_token %}

            <input type="hidden" name="room_id" value="{{r.id}}" id="">
            <div class="form-group">
              <label for="exampleInputUsername1">Room Name</label>
              <input name="room_name" value="{{r.room_name}}" required type="text" class="form-control"
                id="exampleInputUsername1" placeholder="Room Name" />
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Room Capacity</label>
              <input type="text" value="{{r.capacity}}" name="room_cap" required class="form-control"
                id="exampleInputEmail1" placeholder="Room Capacity" />
            </div>
            <div class="form-group">
              <label for="location">Room Location</label>
              <input type="text" value="{{r.location}}" name="room_location" required class="form-control" id="location"
                placeholder="Location" />
            </div>
            <button type="submit" class="btn btn-primary mr-2" onclick="performAction()">
              Edit Room
            </button>
            <button type="reset" data-dismiss="modal" class="btn btn-light">
              Cancel
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{%endfor%}
{%endblock%}