core/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),

    path('login/', views.login_view, name = 'login'),
    path('logout/', views.logout_view, name = 'logout'),
    path('dashboard/', views.dashboard, name='dashboard'),

    path('student/', views.students, name='student'),
    path('student/delete/<int:pk>', views.deleteStudent, name='deleteStudent'),

    path('room/', views.rooms, name='room'),
    path('room/delete/<int:pk>', views.deleteRoom, name='deleteRoom'),

       
    path('staff/', views.staff, name='staff'),
    path('staff/delete/<int:staff_id>', views.delete_staff, name = 'deleteStaff'),

    path('departments/', views.departments, name='departments'),
    path('departments/delete/<int:pk>', views.deleteDept, name='deleteDepartment'),

    path('departments/<str:dpt>/', views.program, name='program'),
    path('program/delete/<int:pk>/', views.deleteProgram, name='deleteProgram'),
    
    path('courses/<str:program>/', views.course, name='course'),
    path('course/delete/<int:pk>/', views.deleteCourse, name='deleteCourse'),
    path('timetable/', views.timetable, name='timetable'),
    path('scheduletimetable/', views.scheduletimetable, name='scheduletimetable'),


    path('settings/', views.settings, name='settings'),
]

staff_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'staff'

urlpatterns = [
        path('dashboard/', views.staff_dashboard, name='dashboard'),
        path('login/', views.login_view, name = 'login'),
        path('logout/', views.logout_view, name = 'logout'),
        path('settings/', views.settings, name = 'settings'),
        path('programs/', views.programs, name = 'programs'),
        path('courses/<str:program>/', views.courses, name='course'),

        path('generate_timetable/', views.generate_timetable_view, name='generate_timetable'),
        path('success/', views.success_view, name='success_view'),
        path('timetable/', views.timetable_view, name='timetable_view'),
    ]

timetable/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('student/', include('student_app.urls')),
    path('staff/', include('staff_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class Department(models.Model):
    department_name = models.CharField(max_length=100)
    department_code = models.CharField(max_length=20)

    def __str__(self):
        return self.department_name

class Program(models.Model):
    program_name = models.CharField(max_length=100)
    program_code = models.CharField(max_length=20)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)

    def __str__(self):
        return self.program_name

class Staff(models.Model):
    ROLE = [('Admin','Admin'),('Lecturer','Lecturer')]
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    fullname = models.CharField(max_length=255)
    username = models.CharField(max_length=255)
    email = models.EmailField()
    password = models.CharField(max_length=255)
    role = models.CharField(max_length=50, choices=ROLE, default='lecturer')

    def delete(self, *args, **kwargs):
        courses = Course.objects.filter(course_lecturer=self)
        for course in courses:
            course.course_lecturer = None
            course.save()
        super().delete(*args, **kwargs)
    

    def __str__(self):
        return self.username
    
class Course(models.Model):
    course_lecturer = models.ForeignKey(Staff, on_delete=models.SET_NULL, null=True, blank=True)
    course_name = models.CharField(max_length=100)
    course_code = models.CharField(max_length=20)
    description = models.TextField()
    program = models.ForeignKey(Program, on_delete=models.CASCADE)
    credit = models.PositiveIntegerField()
    course_year = models.CharField(max_length=40)
  
    def __str__(self):
        return self.course_name
    


    

class Student(models.Model):
    reg_no = models.CharField(max_length=40)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    program = models.ForeignKey(Program, on_delete=models.CASCADE)
    password = models.CharField(max_length=255)
    
    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Room(models.Model):
    room_name = models.CharField(max_length=50)
    capacity = models.PositiveIntegerField()
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.room_name

class TimeSlot(models.Model):
    DAY_CHOICES = (
        ('Monday', 'Monday'),
        ('Tuesday', 'Tuesday'),
        ('Wednesday', 'Wednesday'),
        ('Thursday', 'Thursday'),
        ('Friday', 'Friday'),
        ('Saturday', 'Saturday'),
        ('Sunday', 'Sunday'),
    )

    TIME_RANGE_CHOICES = (
        ('08:00-11:00', '08:00-11:00'),
        ('11:00-14:00', '11:00-14:00'),
        ('14:00-17:00', '14:00-17:00'),
    )

    day = models.CharField(max_length=10, choices=DAY_CHOICES)
    time_range = models.CharField(max_length=11, choices=TIME_RANGE_CHOICES)

    def __str__(self):
        return f"{self.day} - {self.time_range}"
    
class Timetable(models.Model):
    program = models.ForeignKey(Program, on_delete=models.CASCADE)
    year = models.CharField(max_length=10)
    
    def __str__(self):
        return f"Timetable for {self.program.program_name} Year {self.year}"
    

class CourseSchedule(models.Model):
    timetable = models.ForeignKey(Timetable, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    timeslot = models.ForeignKey(TimeSlot, on_delete=models.CASCADE)
    staff = models.ForeignKey(Staff, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.course.course_name} in {self.room.room_name} at {self.timeslot}"

    def save(self, *args, **kwargs):
        self.validate_schedule()
        super().save(*args, **kwargs)

    def validate_schedule(self):
        # Check for room conflicts
        room_conflicts = CourseSchedule.objects.filter(
            room=self.room,
            timeslot=self.timeslot
        ).exclude(id=self.id)
        if room_conflicts.exists():
            raise ValidationError(f"Room {self.room.room_name} is already booked for {self.timeslot}.")

        # Check for staff conflicts
        staff_conflicts = CourseSchedule.objects.filter(
            staff=self.staff,
            timeslot=self.timeslot
        ).exclude(id=self.id)
        if staff_conflicts.exists():
            raise ValidationError(f"Staff {self.staff.username} is already scheduled for another course at {self.timeslot}.")

templates/staff/courses.html
{% extends 'staff/staff_layout.html'%}

{% block content %}
<div class="container">
    <h3 class="text-center">{{ program.program_name }} ({{ program.program_code }})</h3>
    <p>Course Units</p>
    
    </div>
    {% for year, courses_in_year in courses_by_year.items %}
    <div class="card p-3 my-3 bg-white">
        <h5>Year {{ year }}</h5>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Code</th>
                    <th>Course Unit</th>
                    <th>Lecturer</th>
                    <th>Credits</th>
                    
                </tr>
            </thead>
            <tbody>
                {% for c in courses %}
                {% if c.course_year == year %}
                <tr>
                    <td>{{ c.course_code }}</td>
                    <td>{{ c.course_name }}</td>
                    <td>{{c.course_lecturer.fullname}}</td>
                    <td>{{ c.credit }}</td>
                   
                </tr>
                {% endif %}
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% endfor %}
</div>

{%endblock%}

templates/staff/generate_timetable.html
{% extends 'staff/staff_layout.html'%}

{% block content %}
  
<h2>Generate Timetable</h2>

<form method="post">
    {% csrf_token %}
    <label for="program_id">Program:</label>
    <select name="program_id" class="form-control my-2" id="program_id" required>
        <option value="">Select a Program</option>
        {% for program in programs %}
        {% if staff.department == program.department %}
            <option value="{{ program.id }}">{{ program.program_name }}</option>
        {% endif %}
        {% endfor %}
    </select><br><br>
    
    <label for="year">Year:</label>
   
    <select name="year" id="" class="form-control my-2" required>
        <option value="">Choose Year</option>
        <option value="1 I">Year 1 Semister One</option>
        <option value="1 II">Year 1, Semister Two</option>
        <option value="2 I">Year 2, Semister One</option>
        <option value="2 II">Year 2, Semister Two</option>
        <option value="3 I">Year 3, Semister One</option>
        <option value="3 II">Year 3, Semister Two</option>
        <option value="4 I">Year 4, Semister One</option>
        <option value="4 II">Year 4, Semister One</option>
        <option value="5 I">Year 5, Semister Two</option>
        <option value="5 II">Year 5, Semister Two</option>
    </select>

    <button type="submit" class="btn btn-primary">Generate Timetable</button>
</form>




{% endblock %}

templates/staff/login.html
{% load static%}

<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Time Table Generator</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="{% static 'vendors/feather/feather.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/ti-icons/css/themify-icons.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/css/vendor.bundle.base.css' %}">
  <!-- endinject -->
  <!-- Plugin css for this page -->
  <link rel="stylesheet" href="{% static 'vendors/datatables.net-bs4/dataTables.bootstrap4.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/ti-icons/css/themify-icons.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'js/select.dataTables.min.css' %}">
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="{% static 'css/vertical-layout-light/style.css' %}">
  <!-- <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet"> -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

  <!-- endinject -->
  <link rel="shortcut icon" href="images/favicon.png" />
</head>

<body>

  <div class="container-scroller">
    <nav class="navbar col-lg-12 col-12 p-0 fixed-top">
      <div class="navbar-menu-wrapper d-flex align-items-center justify-content-between w-100">
        <div class="navbar-brand-wrapper">
          <a class="navbar-brand brand-logo ml-3 d-flex align-items-center my-2" href="#">
            <img src="{% static 'images/timetable/logolira.png' %}" class="mr-2" alt="Lira University" />
            <p class="text-primary text-bolder" style="font-weight: bolder;font-size: x-large;">Time Table Generator</p>
          </a>
          <a class="navbar-brand brand-logo-mini" href="#">
            <img src="{% static 'images/timetable/logolira.png' %}" alt="logo" />
          </a>
        </div>


        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button"
          data-toggle="offcanvas">
          <span class="icon-menu"></span>
        </button>
      </div>
    </nav>
    <div class="container-fluid full-page-wrapper" style="margin-top: 60px;">
      <div class="content-wrapper d-flex align-items-center auth px-0">
        <div class="row w-100 mx-0">
          <div class="col-lg-4 mx-auto">
            <div class="auth-form-light text-left py-5 px-4 px-sm-5">
              <div class="brand-logo text-center">
                <img src="{% static 'images/timetable/logolira.png' %}" width="50" height="120" alt="logo">
              </div>
              <h4>Hello! Welcome Back</h4>
              <h6 class="font-weight-light">Sign in to continue.</h6>

              {% if messages %}
              {% for message in messages %}
              <h6{% if message.tags %} class="{{ message.tags }} text-danger" {% endif %}>{{ message }}</h6>
              {% endfor %}
              {% endif %}

              

                <form class="pt-3" method="POST">
                  {% csrf_token %}
                  <div class="form-group">
                    <input type="text" name="username" class="form-control form-control-lg" id="exampleInputEmail1"
                      placeholder="Username">
                  </div>
                  <div class="form-group">
                    <input type="password" name="password" class="form-control form-control-lg"
                      id="exampleInputPassword1" placeholder="Password">
                  </div>
                  <div class="mt-3">
                    <input type="submit" class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn"
                      value="Login">
                  </div>
                  <div class="my-2 d-flex justify-content-between align-items-center">

                    <a href="#" class="auth-link text-black">Forgot password?</a>
                  </div>


                </form>
                <a href="{%url 'core:home'%}" class="text-black nav-link text-center">Back to main</a>
            </div>
          </div>
        </div>
      </div>
      <!-- content-wrapper ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->
  <!-- plugins:js -->
  <script src="{% static 'vendors/js/vendor.bundle.base.js' %}"></script>
  <!-- endinject -->
  <!-- Plugin js for this page -->
  <script src="{% static 'vendors/chart.js/Chart.min.js' %}"></script>
  <script src="{% static 'vendors/datatables.net/jquery.dataTables.js' %}"></script>
  <script src="{% static 'vendors/datatables.net-bs4/dataTables.bootstrap4.js' %}"></script>
  <script src="{% static 'js/dataTables.select.min.js' %}"></script>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


  <!-- End plugin js for this page -->
  <!-- inject:js -->
  <script src="{% static 'js/off-canvas.js' %}"></script>
  <script src="{% static 'js/hoverable-collapse.js' %}"></script>
  <script src="{% static 'js/template.js' %}"></script>
  <script src="{% static 'js/settings.js' %}"></script>
  <script src="{% static 'js/todolist.js' %}"></script>
  <!-- endinject -->
  <!-- Custom js for this page-->
  <script src="{% static 'js/dashboard.js' %}"></script>
  <script src="{% static 'js/Chart.roundedBarCharts.js' %}"></script>
  <!-- End custom js for this page-->
</body>

</html>

templates/staff/programs.html
{% extends 'staff/staff_layout.html'%}
{%block content%}
<h6 class="text-center">Programs</h6>
<div class="content-wrapper">

    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-striped ">
                <thead>
                    <tr>
                        <th>Program Name</th>
                        <th>Program Code</th>
                        <!-- <th class="text-center">Actions</th> -->
                    </tr>
                </thead>
                <tbody>
                    {% for p in programs %}
                    {% if staff.department == p.department %}
                    
                    <tr>
                        <td><a href="{% url 'staff:course' program=p.pk %}" class="nav-link">{{ p.program_name }}</a></td>
                        <td>{{ p.program_code }}</td>
                    </tr>
                    {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    
</div>
{%endblock%}

templates/staff/staff_layout.html
{% load static%}

<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Time Table Generator</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="{% static 'vendors/feather/feather.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/ti-icons/css/themify-icons.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/css/vendor.bundle.base.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css'%}">

  <!-- endinject -->
  <!-- Plugin css for this page -->
  <link rel="stylesheet" href="{% static 'vendors/datatables.net-bs4/dataTables.bootstrap4.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/ti-icons/css/themify-icons.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'js/select.dataTables.min.css' %}">
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="{% static 'css/vertical-layout-light/style.css' %}">
  <!-- <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet"> -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

  <!-- endinject -->
  <link rel="shortcut icon" href="images/favicon.png" />
</head>

<body>
  <div class="container-scroller">
    <!-- notification div -->
    <div id="notification" class="notification">Action was successful!</div>

    <!-- partial:partials/_navbar.html -->
    <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
      <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
        <a class="navbar-brand brand-logo ml-5 " href="#"><img src="{% static 'images/timetable/logolira.png' %}"
            class="mr-2" alt="Lira University" />TTG</a>
        <a class="navbar-brand brand-logo-mini" href="#"><img src="{% static 'images/timetable/logolira.png' %}"
            alt="logo" /></a>
      </div>
      <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
        <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
          <span class="icon-menu"></span>
        </button>

        <ul class="navbar-nav navbar-nav-right">
          <li class="nav-item dropdown">
            <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown"
              href="{% url 'staff:settings'%}">
              <i class="ti-settings mx-0"></i>
              <!-- <span class="count"></span> -->
            </a>

            <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list"
              aria-labelledby="notificationDropdown">
              <p class="mb-0 font-weight-normal float-left dropdown-header">Notifications</p>
              <a class="dropdown-item preview-item">
                <div class="preview-thumbnail">
                  <div class="preview-icon bg-success">
                    <i class="ti-info-alt mx-0"></i>
                  </div>
                </div>
                <div class="preview-item-content">
                  <h6 class="preview-subject font-weight-normal">Application Error</h6>
                  <p class="font-weight-light small-text mb-0 text-muted">
                    Just now
                  </p>
                </div>
              </a>
              <a class="dropdown-item preview-item">
                <div class="preview-thumbnail">
                  <div class="preview-icon bg-warning">
                    <i class="ti-settings mx-0"></i>
                  </div>
                </div>
                <div class="preview-item-content">
                  <h6 class="preview-subject font-weight-normal">Settings</h6>
                  <p class="font-weight-light small-text mb-0 text-muted">
                    Private message
                  </p>
                </div>
              </a>
              <a class="dropdown-item preview-item">
                <div class="preview-thumbnail">
                  <div class="preview-icon bg-info">
                    <i class="ti-user mx-0"></i>
                  </div>
                </div>
                <div class="preview-item-content">
                  <h6 class="preview-subject font-weight-normal">New user registration</h6>
                  <p class="font-weight-light small-text mb-0 text-muted">
                    2 days ago
                  </p>
                </div>
              </a>
            </div>
          </li>

        </ul>

        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button"
          data-toggle="offcanvas">
          <span class="icon-menu"></span>
        </button>
      </div>
    </nav>
    <!-- partial -->
    <div class="container-fluid page-body-wrapper">
      <!-- <div id="notification" class="notification">Action was successful!</div> -->


      <!-- partial:partials/_sidebar.html -->
      <nav class="sidebar sidebar-offcanvas position-fixed" id="sidebar">
        <ul class="nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'staff:dashboard'%}">
              <i class="icon-grid menu-icon"></i>
              <span class="menu-title">Dashboard</span>
            </a>
          </li>
          {% if staff.role == 'Admin' %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'staff:programs' %}">
              <i class="fa-solid fa-clock"></i>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              <span class="menu-title">Programs</span>

            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'staff:generate_timetable' %}">
              <i class="fa-solid fa-bars"></i>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              <span class="menu-title">Generate timetable</span>

            </a>
          </li>


          {% endif %}

          <li class="nav-item">
            <a class="nav-link" href="{% url 'staff:timetable_view' %}">
              <i class="fa-solid fa-clock"></i>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              <span class="menu-title">Time Table</span>

            </a>
          </li>


          <li class="nav-item">
            <a class="nav-link" href="{% url 'staff:logout' %}">
              <i class="icon-lock menu-icon"></i>
              <span class="menu-title" onclick="performAction()">Logout</span>

            </a>
          </li>

        </ul>
      </nav>
      <!-- partial -->
      <div class="main-panel" style="margin-left: 250px;">
        <div class="content-wrapper">
          {% block content%}
          {% endblock%}
        </div>
      </div>
    </div>
    <!-- page-body-wrapper ends -->

    <!-- settings modal -->
    <div class="modal fade" id="settings" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
      aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Update Settings</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <form action="" method="POST">
            {% csrf_token %}
            <div class="modal-body">
              <input type="email" placeholder="Email" name="email" class="form-control my-2" required>
              <input type="password" placeholder="Password" name="password" class="form-control my-2" required>
              <input type="passwordConfirm" placeholder="Confirm Password" name="passwordConfirm"
                class="form-control my-2" required>
            </div>
            <div class="modal-footer">
              <button type="reset" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary" onclick="performAction()">Save</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <!-- container-scroller -->

  <!-- plugins:js -->
  <script src="{% static 'vendors/js/vendor.bundle.base.js' %}"></script>
  <script src="{% static 'js/notification.js' %}"></script>
  <!-- endinject -->
  <!-- Plugin js for this page -->
  <script src="{% static 'vendors/chart.js/Chart.min.js' %}"></script>
  <script src="{% static 'vendors/datatables.net/jquery.dataTables.js' %}"></script>
  <script src="{% static 'vendors/datatables.net-bs4/dataTables.bootstrap4.js' %}"></script>
  <script src="{% static 'js/dataTables.select.min.js' %}"></script>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


  <!-- End plugin js for this page -->
  <!-- inject:js -->
  <script src="{% static 'js/off-canvas.js' %}"></script>
  <script src="{% static 'js/hoverable-collapse.js' %}"></script>
  <script src="{% static 'js/template.js' %}"></script>
  <script src="{% static 'js/settings.js' %}"></script>
  <script src="{% static 'js/todolist.js' %}"></script>
  <script src="{% static 'js/currentdate.js' %}"></script>

  <!-- endinject -->
  <!-- Custom js for this page-->
  <script src="{% static 'js/dashboard.js' %}"></script>
  <script src="{% static 'js/Chart.roundedBarCharts.js' %}"></script>
  <!-- End custom js for this page-->
</body>

</html>

templates/staff/success.html
<!-- templates/success.html -->

{% extends 'staff/staff_layout.html'%}

{% block content %}
  <h1>Timetable Generated Successfully</h1>
  <p>The timetable has been generated and saved successfully.</p>
{% endblock %}

templates/staff/timetable.html
{% extends 'staff/staff_layout.html'%}

{% block content %}
<div class="content-wrapper">
   
<h2 class="text-center">Timetables</h2>
<div class="container">
     
    {% if timetables %}
    {% for timetable in timetables %}
        {% if timetable.program.department == staff.department %}
        <h3 class="mt-5">Timetable for {{ timetable.program.program_name }} Year {{ timetable.year }}</h3>
        <table class="table table-bordered table-striped">
            <thead class="bg-primary text-white">
                <tr>
                    <th>Day</th>
                    <th>Timeslot</th>
                    <th>Course</th>
                    <th>Lecturer</th>
                    <th>Room</th>
                </tr>
            </thead>
            <tbody>
                {% for schedule in timetable.courseschedule_set.all %}
                    <tr>
                        <td>{{ schedule.timeslot.day }}</td>
                        <td>{{ schedule.timeslot.time_range }}</td>
                        <td>{{ schedule.course.course_name }}</td>
                        <td>{{ schedule.staff.fullname }}</td>
                        <td>{{ schedule.room.room_name }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p>No timetables available.</p>
        {% endif %}
        {% endfor %}


    
{% else %}
    <p>No timetables available.</p>
{% endif %}
</div>





</div>

{%endblock%}